### PR TITLE
Fix '-str' handling for the glob import to enable 'importstr'.

### LINKED ISSUE #3: GlobImporter - bug in importstr handling
# Issue
Using the "glob-str" prefix is completely ignored.

# Current behavior
Instead of having an "importstr" as a result. The GlobImporter throws an error about "unknown prefix"

# Expected behavior
The GlobImporter doesn't return an issue, but creates the expected "importstr".

# Code base
https://github.com/peterbueschel/jsonnet-custom-importers/blob/b193b4ea83bbdabbfde87493cc026d7002e24b3f/glob.go#L300 Here the `strings.HasPrefix(prefix, "-str")` isn't testing the right part of the prefix. The prefix looks like `glob-str.<?>`. So, the prefix of the prefix is not just `-str`, but `glob-str`.

# Possible Fix
Test instead for `glob-str`.

### PR DESCRIPTION
**Pull request by peterbueschel**
- Fix glob examples in the readme file.
- Remove old exclude pattern example from the readme file.

### CODE REVIEW

File: glob_test.go [hunk 1]
```diff
@@ -337,3 +337,71 @@ func TestGlobImporter_Import(t *testing.T) {
...
+		prefix string
+	}
+	tests := []struct {
+		name    string
+		fields  fields
+		args    args
+		want    string
+		wantErr bool
+	}{
+		{
```
Comment (peterbueschel) [inline glob_test.go:356]: Add more tests for the different glob prefixa.
